<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RoutingService.Domain\RoutingService.Domain.csproj" />
    <ProjectReference Include="..\RoutingService.Facade\RoutingService.Facade.csproj" />
  </ItemGroup>

</Project>
