// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TerminalService.Infrastructure;

#nullable disable

namespace TerminalService.Infrastructure.Migrations
{
    [DbContext(typeof(EFAppContext))]
    partial class EFAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TerminalService.Domain.Entities.Terminal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("DailyCapacity")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Location", "TerminalService.Domain.Entities.Terminal.Location#Location", b1 =>
                        {
                            b1.IsRequired();

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Address", "TerminalService.Domain.Entities.Terminal.Location#Location.Address#Address", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Street")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("Street");

                                    b2.Property<int>("StreetNumber")
                                        .HasColumnType("integer")
                                        .HasColumnName("StreetNumber");

                                    b2.ComplexProperty(typeof(Dictionary<string, object>), "City", "TerminalService.Domain.Entities.Terminal.Location#Location.Address#Address.City#City", b3 =>
                                        {
                                            b3.IsRequired();

                                            b3.Property<string>("CityName")
                                                .IsRequired()
                                                .HasColumnType("text")
                                                .HasColumnName("CityName");

                                            b3.Property<int>("ZipCode")
                                                .HasColumnType("integer")
                                                .HasColumnName("ZipCode");
                                        });
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Region", "TerminalService.Domain.Entities.Terminal.Location#Location.Region#Region", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Country")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("Country");

                                    b2.Property<string>("MainRegion")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("MainRegion");

                                    b2.Property<string>("SubRegion")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("SubRegion");
                                });
                        });

                    b.HasKey("Id");

                    b.ToTable("Terminal", (string)null);
                });

            modelBuilder.Entity("TerminalService.Domain.Entities.TerminalAllocation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TerminalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TrackingNumber")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "AllocationDate", "TerminalService.Domain.Entities.TerminalAllocation.AllocationDate#Date", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime>("DateTime")
                                .HasColumnType("timestamp with time zone");
                        });

                    b.HasKey("Id");

                    b.HasIndex("TerminalId", "Version")
                        .IsUnique();

                    b.ToTable("TerminalAllocation", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
