openapi: 3.0.3
info:
  title: Terminal Service API
  version: 1.1.0
  description: |
    API for handling terminal allocation of parcels in the event-driven parcel system.
    And generel Terminal metadata
    
paths:
  /terminal:
    post:
      summary: Process new terminal allocation request
      description: |
        Receives an terminal allocation Request and tries to allocate it and publish result
      operationId: processAllocationRequest
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AllocationRequestEvent'
      responses:
        '201':
          description: Allocation created
        '400':
          $ref: '#/components/responses/400Error'
        '500':
          $ref: '#/components/responses/500Error'
        '409':
          $ref: '#/components/responses/409Error'

  /terminal/{id}:
    get:
      summary: Returns terminal based om ID
      description: |
        Returns a terminal with the given ID exists
      operationId: getTerminalById
      parameters:
        - name: id
          in: path
          required: true
          description: Terminal ID
          schema:
            type: string
            format: uuid
      responses:
        '200':
          $ref: '#/components/responses/Terminal200Response'
        '404':
          $ref: '#/components/responses/404Error'
        '500':
          $ref: '#/components/responses/500Error'

components:
  responses:
    Terminal200Response:
      description: Get Terminal
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Terminal'

    400Error:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BadResponse'

    500Error:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BadResponse'

    409Error:
      description: Conflict/Concurrency
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BadResponse'

    404Error:
      description: Terminal not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BadResponse'

  schemas:
    BadResponse:
      type: object
      properties:
        message:
          type: string
          example: "Invalid request data"

    AllocationRequestEvent:
      type: object
      required:
        - trackingNumber
        - terminalId

      properties:
        trackingNumber:
          type: string
          format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000"

        terminalId:
          type: string
          format: uuid
          example: "30000000-0000-0000-0000-000000000009"


    Terminal:
      type: object
      required:
        - id
        - type
        - currentlyReserved
        - dailyCapacity
        - location
      properties:
        id:
          type: string
          format: uuid
          example: "30000000-0000-0000-0000-000000000009"

        type:
          $ref: '#/components/schemas/TerminalType'

        currentlyReserved:
          type: integer
          format: int32
          example: 20

        dailyCapacity:
          type: integer
          format: int32
          example: 120

        location:
          $ref: '#/components/schemas/Location'

      example:
        id: "20000000-0000-0000-0000-000000000009"
        type: "DistributionCenter"
        dailyCapacity: 120
        location:
          region:
            country: "Denmark"
            mainRegion: "Jylland"
            subRegion: "Horsens"
          address:
            city:
              name: "Horsens"
            street: "Havnevej"
            streetNumber: 12

    TerminalType:
      type: string
      description: Enum placeholder for terminal types
      enum:
        - Hub
        - PickupPoint
        - DistributionCenter
      example: "DistributionCenter"

    Location:
      type: object
      required:
        - region
        - address
      properties:
        region:
          $ref: '#/components/schemas/Region'
        address:
          $ref: '#/components/schemas/Address'
      example:
        region:
          country: "Denmark"
          mainRegion: "Jylland"
          subRegion: "Horsens"
        address:
          city:
            name: "Horsens"
          street: "Havnevej"
          streetNumber: 12

    Region:
      type: object
      required:
        - country
        - mainRegion
        - subRegion
      properties:
        country:
          type: string
          example: "Denmark"
        mainRegion:
          type: string
          example: "Jylland"
        subRegion:
          type: string
          example: "Horsens"

    Address:
      type: object
      required:
        - city
        - street
        - streetNumber
      properties:
        city:
          $ref: '#/components/schemas/City'
        street:
          type: string
          example: "Havnevej"
        streetNumber:
          type: integer
          format: int32
          example: 12
      example:
        city:
          name: "Horsens"
        street: "Havnevej"
        streetNumber: 12

    City:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          example: "Horsens"
      example:
        name: "Horsens"