<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\Shared.csproj" />
    <ProjectReference Include="..\TerminalService.Domain\TerminalService.Domain.csproj" />
    <ProjectReference Include="..\TerminalService.Facade\TerminalService.Facade.csproj" />
  </ItemGroup>

</Project>
