# Secret with PostgreSQL connection string
apiVersion: v1
kind: Secret
metadata:
  name: parcel-db-secret
type: Opaque
stringData:
  connectionString: "Host=parcel-db;Port=5432;Database=parceldb;Username=user;Password=root"