<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\Shared.csproj" />
    <ProjectReference Include="..\AllocationService.Domain\AllocationService.Domain.csproj" />
    <ProjectReference Include="..\AllocationService.Facade\AllocationService.Facade.csproj" />
    <ProjectReference Include="..\AllocationService.UseCase\AllocationService.UseCase.csproj" />	
  </ItemGroup>
	<ItemGroup>
		<PackageReference Include="Dapr.Client" />
	</ItemGroup>

</Project>
