# Secret with PostgreSQL connection string
apiVersion: v1
kind: Secret
metadata:
  name: routing-db-secret
type: Opaque
stringData:
  connectionString: "Host=routing-db;Port=5432;Database=routingdb;Username=user;Password=root"