# ParcelService Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: routingservice
  labels:
    app: routingservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: routingservice
  template:
    metadata:
      labels:
        app: routingservice
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "routingservice"
        dapr.io/app-port: "8002"
        dapr.io/enable-api-logging: "true"
    spec:
      containers:
        - name: routingservice
          image: ghcr.io/mikkelrlarsen/routingservice:latest
          ports:
            - containerPort: 8002
          imagePullPolicy: Always
          env:
            - name: ConnectionStrings__routingdb
              valueFrom:
                secretKeyRef:
                  name: routing-db-secret
                  key: connectionString