apiVersion: v1
kind: Service
metadata:
  name: routingservice-service
  labels:
    app: routingservice-service
spec:
  type: LoadBalancer
  selector: 
    app: routingservice
  ports:
    - port: 8002
      targetPort: 8002