# PersistentVolumeClaim for PostgreSQL to ParcelService
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: terminal-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi