<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\AllocationService.Facade\AllocationService.Facade.csproj" />
	  <ProjectReference Include="..\AllocationService.Infrastructure\AllocationService.Infrastructure.csproj" />
	  <ProjectReference Include="..\AllocationService.UseCase\AllocationService.UseCase.csproj" />
	</ItemGroup>

</Project>
