//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

using Dapr;
using Microsoft.AspNetCore.Mvc;
using RoutingService.Api.DataTransferObjects;
using Shared;
using System.CodeDom.Compiler;
using System.Threading.Tasks;


#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 612 // Disable "CS0612 '...' is obsolete"
#pragma warning disable 649 // Disable "CS0649 Field is never assigned to, and will always have its default value null"
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
#pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"
#pragma warning disable 3016 // Disable "CS3016 Arrays as attribute arguments is not CLS-compliant"
#pragma warning disable 8600 // Disable "CS8600 Converting null literal or possible null value to non-nullable type"
#pragma warning disable 8602 // Disable "CS8602 Dereference of a possibly null reference"
#pragma warning disable 8603 // Disable "CS8603 Possible null reference return"
#pragma warning disable 8604 // Disable "CS8604 Possible null reference argument for parameter"
#pragma warning disable 8625 // Disable "CS8625 Cannot convert null literal to non-nullable reference type"
#pragma warning disable 8765 // Disable "CS8765 Nullability of type of parameter doesn't match overridden member (possibly because of nullability attributes)."

namespace RoutingService.Api.Controllers
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public interface IRoutingController
    {

        /// <summary>
        /// Process new parcel routing
        /// </summary>

        /// <remarks>
        /// Receives a new parcel event and initiates routing logic.
        /// <br/>Determines the route between sender and receiver terminals.
        /// </remarks>

        /// <returns>Routing processed successfully</returns>

        System.Threading.Tasks.Task ProcessNewParcelAsync(NewParcelEvent body);

        /// <summary>
        /// Informs SAGA that a parcel was allocated
        /// </summary>

        /// <remarks>
        /// Receives a allocation recieved event and informs orchestration SAGA.
        /// </remarks>

        /// <returns>Event received successfully</returns>

        System.Threading.Tasks.Task ProcessAllocationReceivedAsync(AllocationReceivedEvent body);

    }

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class RoutingController : Shared.ApiControllerBase
    {
        private IRoutingController _implementation;

        public RoutingController(IRoutingController implementation)
        {
            _implementation = implementation;
        }

        /// <summary>
        /// Process new parcel routing
        /// </summary>
        /// <remarks>
        /// Receives a new parcel event and initiates routing logic.
        /// <br/>Determines the route between sender and receiver terminals.
        /// </remarks>
        /// <returns>Routing processed successfully</returns>
        [Microsoft.AspNetCore.Mvc.HttpPost, Microsoft.AspNetCore.Mvc.Route("routing/newparcelevent")]
		[Topic("daprpubsub", "new-parcel")]
		public System.Threading.Tasks.Task ProcessNewParcel([Microsoft.AspNetCore.Mvc.FromBody] NewParcelEvent body)
        {

            return _implementation.ProcessNewParcelAsync(body);
        }

        /// <summary>
        /// Informs SAGA that a parcel was allocated
        /// </summary>
        /// <remarks>
        /// Receives a allocation recieved event and informs orchestration SAGA.
        /// </remarks>
        /// <returns>Event received successfully</returns>
        [Microsoft.AspNetCore.Mvc.HttpPost, Microsoft.AspNetCore.Mvc.Route("routing/allocationreceivedevent")]
		[Topic("daprpubsub", "allocation-received")]
		public System.Threading.Tasks.Task ProcessAllocationReceived([Microsoft.AspNetCore.Mvc.FromBody] AllocationReceivedEvent body)
        {

            return _implementation.ProcessAllocationReceivedAsync(body);
        }

    }

    


}

#pragma warning restore  108
#pragma warning restore  114
#pragma warning restore  472
#pragma warning restore  612
#pragma warning restore  649
#pragma warning restore 1573
#pragma warning restore 1591
#pragma warning restore 8073
#pragma warning restore 3016
#pragma warning restore 8600
#pragma warning restore 8602
#pragma warning restore 8603
#pragma warning restore 8604
#pragma warning restore 8625
#pragma warning restore 8765