// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RoutingService.Infrastructure;

#nullable disable

namespace RoutingService.Infrastructure.Migrations
{
    [DbContext(typeof(EFAppContext))]
    partial class EFAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RoutingService.Domain.Edge", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("From")
                        .HasColumnType("uuid");

                    b.Property<Guid>("To")
                        .HasColumnType("uuid");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("From");

                    b.ToTable("Edge", (string)null);
                });

            modelBuilder.Entity("RoutingService.Domain.Terminal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Region", "RoutingService.Domain.Terminal.Region#Region", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Country");

                            b1.Property<string>("MainRegion")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("MainRegion");

                            b1.Property<string>("SubRegion")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("SubRegion");
                        });

                    b.HasKey("Id");

                    b.ToTable("Terminal", (string)null);
                });

            modelBuilder.Entity("RoutingService.Domain.Edge", b =>
                {
                    b.HasOne("RoutingService.Domain.Terminal", null)
                        .WithMany("Edges")
                        .HasForeignKey("From")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RoutingService.Domain.Terminal", b =>
                {
                    b.Navigation("Edges");
                });
#pragma warning restore 612, 618
        }
    }
}
